testing

diff --git a/eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml b/eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
--- a/eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
+++ b/eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
@@ -74,10 +74,10 @@ extends:
 
           - pwsh: |
               Write-Host "##[group]Package contoso.management"
-              Write-Host "   ##[section]Start of a Subsection"
-              Write-Host "   ##[error]The generation process failed. Please check the logs for details."
+              Write-Host "##[section]Start of a Subsection"
+              Write-Host "##[error]The generation process failed. Please check the logs for details."
               Write-Host "##[endgroup]"
-              exit 0
+              Write-Host "##vso[task.setvariable variable=BuildHasErrors;]true"
               $tspConfigPathPattern = '^specification\/([^\/]+\/)+tspconfig\.yaml$'
               $readmePathPattern = '^specification\/([^\/]+\/){2,}readme\.md$'
               if (('${{ parameters.ConfigType }}' -eq 'TypeSpec') -and ('${{ parameters.ConfigPath }}' -notmatch $tspConfigPathPattern)) {
@@ -146,6 +146,9 @@ extends:
               SkipCheckoutNone: true
 
           - script: |
+              if ["$BuildHasErrors" = "true"]; then
+                exit 1
+              fi
               if [ "${{ parameters.SpecRepoCommit }}" = "$(Build.SourceBranch)" ]; then
                 cd $(SpecRepoDirectory)
                 default_commit=$(git rev-parse HEAD)
